baseURL: "https://johnkamm.github.io/spaw-video/"
languageCode: "en-us"
title: "Southpaw Strategies"

# Ensure assets are served correctly
canonifyURLs: true
relativeURLs: false

# Build settings
publishDir: "public"

# Asset handling
assetDir: "assets"
staticDir: ["static"]

# Markup settings
markup:
  goldmark:
    renderer:
      unsafe: true