baseURL = 'https://spstrat.com/'
languageCode = 'en-us'
title = 'Southpaw Strategies'

canonifyURLs = true
relativeURLs = false
publishDir = "public"
assetDir = "assets"
staticDir = ["static"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true